#include <stdio.h>
#include <string.h>
#include "ecies.h"

#define err(fmt, ...)                                \
        do {                                         \
                printf("ERROR:" fmt, ##__VA_ARGS__); \
                exit(1);                             \
        } while (0)

#define log(fmt, ...)                       \
        do {                                \
                printf(fmt, ##__VA_ARGS__); \
        } while (0)


int main(int argc, char * argv[])
{
    EC_KEY *ec_key = NULL; // EC key from key file

    // Receiver's EC Key (public, private, curve)
    uint8_t *pubk      = NULL;
    uint32_t   pubk_len  = 0;
    uint8_t *privk     = NULL;
    uint32_t   privk_len = 0;
    int      curve;

    // Transmitter's ephemeral public EC Key
    uint8_t *epubk     = NULL;
    uint32_t   epubk_len = 0;

    // AES-GCM encrypted data (IV, authentication tag, ciphertext)
    uint8_t *iv             = NULL;
    uint8_t  iv_len         = 0;
    uint8_t *tag            = NULL;
    uint8_t  tag_len        = 0;
    uint8_t *ciphertext     = NULL;
    uint32_t  ciphertext_len = 0;
    uint8_t *message        = 0;

    // payload details
    char *payload_fname = "payload.enc";

    uint8_t *epubk_r      = NULL;
    uint32_t   epubk_len_r  = 0;
    uint8_t *iv_r             = NULL;
    uint8_t  iv_len_r         = 0;
    uint8_t *tag_r            = NULL;
    uint8_t  tag_len_r        = 0;
    uint8_t *ciphertext_r     = NULL;
    uint32_t  ciphertext_len_r = 0;

    if (argc != 3)
        err("Specify init key file in DER format and message within quotes\n"
            "Usage: %s <file.der> <\"message\">\n", argv[0]);

    /* assign the message to be encrypted to "message" from arg */
    message = (uint8_t *)argv[2];

    /* Loads the initialization EC key. */
    ecies_load_init_key(argv[1], &ec_key, &curve,
                        &pubk, &pubk_len, &privk, &privk_len);

    /*
     * Now initialization key loaded:
     *   - 'ppub'  holds the public key in uncompressed binary format
     *   - 'ppriv' holds the private key in binary format
     *   - 'curve' holds the curve name in ID format
     */
    log("\n --> Encrypt the data by generating ephemeral key pair <--\n\n");

    /* ECIES encrypting the message */
    ecies_encrypt_message(  message, (strlen((const char *)message) + 1),
                            curve, pubk, pubk_len,
                            &epubk, &epubk_len,
                            &iv, &iv_len, &tag, &tag_len,
                            &ciphertext, &ciphertext_len);
    /*
     * Now message is encrypted:
     *   - 'epubk'      holds the ephemeral public key in uncompressed
     *                  binary format, generated by the transmitter
     *   - 'iv'         holds the IV used for the AES-GCM encrypted data
     *   - 'tag'        holds the AES-GCM auth tag of the encrypted data
     *   - 'ciphertext' holds encrypted message data
     */
    log("\n--> Write curve, ephemeral public key, IV, tag, ciphertxt to the payload.enc file<--\n\n");
    ecies_encrypted_payload_write(
                                      payload_fname,
                                      curve,
                                      epubk,epubk_len,
                                      iv,iv_len,
                                      tag,tag_len,
                                      ciphertext,ciphertext_len);

    log("\n--> ecies_encrypted_payload_write finished, output written into payload.enc <--\n\n");

    free(iv);
    free(tag);
    free(ciphertext);
    free(epubk);
    free(pubk);
    free(privk);

    return 0;
}